### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**
Rewrite commit history (up to the last release) based on https://github.com/FlowingCode/DevelopmentConventions

### CODE REVIEW

**Comment by javier-godoy** [comment]
8909f7b refactor(demo): change demo route to error-window

The change to assembly.xml goes into 6e4f355 (ci) or as a standalone commit, instead of piggybacking e18ee53 (test)

**Comment by ngonzalezpazFC** [comment]
> 
> 
> [8909f7b](https://github.com/FlowingCode/ErrorWindowAddon/commit/8909f7bfa5c915c4c9089f43fe0ff03fe1623b71) refactor(demo): change demo route to error-window
> 
> The change to assembly.xml goes into [6e4f355](https://github.com/FlowingCode/ErrorWindowAddon/commit/6e4f3558bfe4af701929ee334fe8396d243ba2c2) (ci) or as a standalone commit, instead of piggybacking [e18ee53](https://github.com/FlowingCode/ErrorWindowAddon/commit/e18ee53ecbc2802d7f85c9b94cc6b4d84f03afc9) (test)

Done

**Comment by javier-godoy** [comment]
@ngonzalezpazFC please review

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC please review

LGTM

**Pull request merged**
